/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MemeCoinFactory: {
<<<<<<< HEAD
      address: "0xe1aa25618fa0c7a1cfdab5d6b456af611873b629",
=======
      address: "0x0c8e79f3534b00d9a3d4a856b665bf4ebc22f2ba",
>>>>>>> 444bbab (Fix Featured Tokens Update Logic)
      abi: [
        {
          type: "function",
          name: "getTokenMetadata",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct MemeCoinFactory.TokenMetadata",
              components: [
                {
                  name: "maxCap",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "symbol",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "image",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mintNewToken",
          inputs: [
            {
              name: "_maxCap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoin",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tokenMetadata",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "maxCap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
<<<<<<< HEAD
      deploymentFile: "run-1749726674.json",
      deploymentScript: "Deploy.s.sol",
    },
    LaunchPad: {
      address: "0xe1da8919f262ee86f9be05059c9280142cf23f48",
=======
      deploymentFile: "run-1748127452.json",
      deploymentScript: "Deploy.s.sol",
    },
    LaunchPad: {
      address: "0xed1db453c3156ff3155a97ad217b3087d5dc5f6e",
>>>>>>> 444bbab (Fix Featured Tokens Update Logic)
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_memeFactory",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MAX_CAP",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "buy",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "featuredTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeQueue",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAuction",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getFeaturedTokenAddresses",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getFeaturedTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "contract MemeCoin[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRecentTokenAddresses",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRecentTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "contract MemeCoin[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "launchNewMeme",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoin",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "memeFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoinFactory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recentTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeQueue",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sell",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tokenToAuction",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "Buy",
          inputs: [
            {
              name: "buyer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "price",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokenTotalSupply",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Launch",
          inputs: [
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MemeLaunched",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "auction",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Sell",
          inputs: [
            {
              name: "seller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "refund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenCreated",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenAddress",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
<<<<<<< HEAD
      deploymentFile: "run-1749726674.json",
=======
      deploymentFile: "run-1748127452.json",
>>>>>>> 444bbab (Fix Featured Tokens Update Logic)
      deploymentScript: "Deploy.s.sol",
    },
  },
  48898: {
    MemeCoinFactory: {
      address: "0x559d4a81e50df2141fa5fa6e61ba1207f139a7a7",
      abi: [
        {
          type: "function",
          name: "getTokenMetadata",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct MemeCoinFactory.TokenMetadata",
              components: [
                {
                  name: "maxCap",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "symbol",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "image",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mintNewToken",
          inputs: [
            {
              name: "_maxCap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoin",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tokenMetadata",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "maxCap",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1747453584.json",
      deploymentScript: "Deploy.s.sol",
    },
    LaunchPad: {
      address: "0x78515e569ae95e861a26e49f75b21d08e582cf16",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_memeFactory",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "MAX_CAP",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "buy",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "featuredTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeQueue",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAuction",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getFeaturedTokenAddresses",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getFeaturedTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "contract MemeCoin[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRecentTokenAddresses",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getRecentTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "contract MemeCoin[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "launchNewMeme",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoin",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "memeFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeCoinFactory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recentTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MemeQueue",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sell",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tokenToAuction",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "Buy",
          inputs: [
            {
              name: "buyer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "price",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokenTotalSupply",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Launch",
          inputs: [
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MemeLaunched",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "auction",
              type: "address",
              indexed: false,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Sell",
          inputs: [
            {
              name: "seller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "refund",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TokenCreated",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tokenAddress",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "image",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1747453584.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
